import {randomBytes,createHash} from 'node:crypto';
const digest=s=>createHash('sha256').update(s).digest('hex');
export function affiliateStore(db,mode,{now=Date.now}={}){
 db.exec("CREATE TABLE IF NOT EXISTS affiliate_referrals(token_hash TEXT PRIMARY KEY,partner_id TEXT NOT NULL,slug TEXT NOT NULL,expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS affiliate_commissions(order_id TEXT PRIMARY KEY,partner_id TEXT NOT NULL,mode TEXT NOT NULL,rate_bps INTEGER NOT NULL,basis_cents INTEGER NOT NULL,gross_cents INTEGER NOT NULL,created_at TEXT NOT NULL)");
 function visit(partner){if(!partner?.id||!partner.slug)throw Error('Approved partner required');db.prepare('DELETE FROM affiliate_referrals WHERE expires<=?').run(now());if(db.prepare('SELECT count(*) n FROM affiliate_referrals').get().n>=100000)throw Error('Referral storage full');const token=randomBytes(32).toString('hex');db.prepare('INSERT INTO affiliate_referrals VALUES(?,?,?,?)').run(digest(token),partner.id,partner.slug,now()+30*86400000);return token;}
 function resolve(token,find){if(!/^[a-f0-9]{64}$/.test(token||''))return null;const r=db.prepare('SELECT * FROM affiliate_referrals WHERE token_hash=? AND expires>?').get(digest(token),now());if(!r)return null;const p=find(r.slug);return p?.id===r.partner_id?{id:p.id,slug:p.slug}:null;}
 function accrue(order){if(!order.partner_id||order.mode!==mode||order.status!==(mode==='sandbox'?'paid_sandbox':'paid_live'))return;db.prepare('INSERT OR IGNORE INTO affiliate_commissions VALUES(?,?,?,?,?,?,?)').run(order.id,order.partner_id,mode,500,order.retail_cents,Math.floor(order.retail_cents/20),new Date().toISOString());}
 function summary(id){const c=db.prepare('SELECT * FROM affiliate_commissions WHERE order_id=? AND mode=?').get(id,mode);if(!c)return null;const o=db.prepare('SELECT total_cents FROM orders WHERE id=?').get(id);const refunds=db.prepare('SELECT amount,status FROM refunds WHERE order_id=?').all(id);const refunded=refunds.filter(r=>r.status==='succeeded').reduce((n,r)=>n+r.amount,0);const pending=refunds.some(r=>['pending','requires_action'].includes(r.status));const total=o.total_cents;const net=Number.isSafeInteger(total)&&total>0?Number(BigInt(c.basis_cents)*BigInt(Math.max(0,total-refunded))*5n/(BigInt(total)*100n)):0;return {...c,netCommissionCents:net,reversedCents:c.gross_cents-net,pendingRefund:pending,fulfillmentHold:Boolean(db.prepare('SELECT hold FROM refund_checks WHERE order_id=?').get(id)?.hold),payableCents:0,state:mode==='sandbox'?'simulation':pending?'refund_review':'unreleased',refundAllocation:'proportional to total paid including tax; commission basis excludes tax and separate shipping'};}
 return {visit,resolve,accrue,summary,list:partner=>db.prepare('SELECT order_id FROM affiliate_commissions WHERE partner_id=? AND mode=? ORDER BY created_at DESC').all(partner,mode).map(r=>summary(r.order_id))};
}
export function referralToken(req){return req.headers.cookie?.split(';').map(s=>s.trim()).find(s=>s.startsWith('fit_referral='))?.slice(13)||'';}
