import test from 'node:test';
import assert from 'node:assert/strict';
import {createCustomerTracking,createTrackingRoute,trackingPage} from './customer-tracking.mjs';
import {createProductCheckoutRoute} from './product-checkout.mjs';
test('tracking links are unguessable, order bound, and expose only customer-safe data',()=>{
 let state='shipped',hold=false,mode='live',webhook=true;const orders={get:id=>({id,mode,status:'paid_live',product_name:'<script>bad</script>',owner_hash:'secret'}),hasWebhook:()=>webhook,refunds:{summary:()=>({fulfillmentHold:hold})}};const t=createCustomerTracking({path:':memory:',orders,worker:{summary:()=>({state,trackingNumber:'123',trackingProvider:'UPS',supplierReference:'private-cj',lastError:'internal',updatedAt:'2026-09-17'})}});
 try{const link=new URL(t.link('one'),'https://example.com'),key=link.searchParams.get('key');assert.equal(t.resolve('two',key),null);assert.equal(t.resolve('one','0'.repeat(64)),null);const r=t.resolve('one',key);assert.equal(r.status,'Shipped');assert.equal(r.tracking,'123');assert.ok(!JSON.stringify(r).includes('private-cj'));assert.ok(!trackingPage(r).includes('<script>'));state='ready';assert.equal(t.resolve('one',key).tracking,null);hold=true;assert.equal(t.resolve('one',key).status,'Order under review');mode='sandbox';assert.equal(t.link('one'),null);assert.equal(t.resolve('one',key),null);mode='live';webhook=false;assert.equal(t.link('one'),null);}finally{t.close();}
});
test('tracking route rejects missing links and prevents caching or referral leakage',async()=>{const route=createTrackingRoute({resolve:()=>null});const res={writeHead(s,h){this.status=s;this.headers=h;},end(b){this.body=b;}};await route({method:'GET'},res,new URL('https://example.com/orders/track?order=known'));assert.equal(res.status,404);assert.equal(res.headers['Referrer-Policy'],'no-referrer');assert.equal(res.headers['Cache-Control'],'private, no-store');});
test('closed checkout still serves private verified tracking link only after webhook confirmation',async()=>{
 let confirmed=true,calls=0;const route=createProductCheckoutRoute({mode:'live',checkout:{enabled:()=>false,verifyProduct:async(id,owner)=>{assert.equal(owner,'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');return {paid:true,webhookReceived:confirmed,orderId:'one',totalCents:1000};}},customerTracking:{link(id){calls++;return '/orders/track?order=one&key=secret';}}});const res={writeHead(s){this.status=s},end(b){this.body=b;}};const req={method:'GET',headers:{cookie:'fit_live_product=aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'}};
 await route(req,res,new URL('https://example.com/checkout/live/result?session_id=cs_live_one'));assert.equal(res.status,200);assert.match(res.body,/Track your order/);assert.equal(calls,1);confirmed=false;await route(req,res,new URL('https://example.com/checkout/live/result?session_id=cs_live_one'));assert.ok(!res.body.includes('key=secret'));assert.equal(calls,1);await route({method:'GET',headers:{}},res,new URL('https://example.com/checkout/live/result?session_id=cs_live_one'));assert.equal(res.status,400);assert.equal(calls,1);
});
