export function homeContent(prefix = '') {
  const link = slug => `${prefix}/category/${slug}`;
  const tiles = [
    ['cleaning','01','Cleaning','A little less elbow grease.','✦'],
    ['organization','02','Organization','Make room for everyday life.','▤'],
    ['kitchen','03','Kitchen','From meal prep to the last dish.','◒'],
    ['tools','04','Tools','For your next “I can fix that.”','↗'],
    ['home-improvement','05','Home improvement','Small projects. Fresh possibilities.','⌂']
  ];
  return `<main id="top" class="home">
    <section class="home-hero shell">
      <div class="home-copy"><p class="eyebrow">GOOD FINDS. EVERYDAY FIXES.</p><h1>Small fixes.<br><em>Better home.</em></h1><p class="home-lede">For the cluttered drawer. The stubborn corner. The little job you’ve been meaning to do. Find a better way to tackle everyday life.</p><div class="home-actions"><a class="primary" href="#browse">Find your next fix <span>↗</span></a><a class="text-link" href="${link('cleaning')}">Explore household finds →</a></div><p class="home-preview">Explore our growing catalog · Checkout coming soon</p></div>
      <div class="home-visual"><img src="/hero-products.png" alt="Kitchen and household problem-solvers arranged together"><div class="home-stamp">LESS FUSS.<br><b>More living.</b></div><a class="home-image-link" href="${link('kitchen')}"><span>START IN THE KITCHEN<br><b>Little upgrades, everyday usefulness.</b></span><span>↗</span></a></div>
    </section>
    <div class="home-values shell"><span>Household problem-solvers</span><span>Five categories to explore</span><span>A home that works for you</span></div>
    <section class="home-section shell" id="browse"><div class="home-heading"><div><p class="eyebrow">WHERE COULD LIFE BE EASIER?</p><h2>Find your kind of fix.</h2></div><p>A place for every project.<br>A possibility in every category.</p></div><div class="home-categories">${tiles.map(([slug,num,name,desc,icon])=>`<a href="${link(slug)}" class="home-tile"><span class="home-tile-top"><span>${num}</span><span>↗</span></span><span class="home-icon" aria-hidden="true">${icon}</span><h3>${name}</h3><p>${desc}</p></a>`).join('')}</div></section>
    <section class="home-feature shell"><div><p class="eyebrow">THE HOUSEHOLD EDIT</p><h2>Less mess.<br>More breathing room.</h2><p>Explore cleaning tools and storage ideas for the spaces you use most.</p><a class="primary" href="${link('organization')}">Explore organization ↗</a></div><div class="home-feature-stack"><a href="${link('cleaning')}"><span>01 / RESET</span><h3>Take on the hard-to-reach.</h3><p>Browse cleaning tools →</p></a><a href="${link('organization')}"><span>02 / RECLAIM</span><h3>Give everything a place.</h3><p>Browse storage ideas →</p></a></div></section>
    <section class="home-section shell" id="best"><div class="home-heading"><div><p class="eyebrow">EVERYDAY INSPIRATION</p><h2>Small ideas. Useful possibilities.</h2></div><p>Explore the category to find available options.</p></div><div class="home-ideas"><a href="${link('kitchen')}"><span class="home-idea-art">↔</span><div><p class="eyebrow">KITCHEN</p><h3>Silicone Stove-Gap Covers</h3><p>A simple idea for the gap that catches everything.</p><b>Explore kitchen finds ↗</b></div></a><a href="${link('kitchen')}"><span class="home-idea-art">▦</span><div><p class="eyebrow">MEAL PREP</p><h3>Vegetable Chopper</h3><p>Discover tools for the daily prep routine.</p><b>Explore kitchen finds ↗</b></div></a><a href="${link('organization')}"><span class="home-idea-art">⇥</span><div><p class="eyebrow">ORGANIZATION</p><h3>Pull-Out Cabinet Organizer</h3><p>Bring the back of the cupboard within reach.</p><b>Explore organization ↗</b></div></a></div></section>
    <section class="home-discovery shell"><div><p class="eyebrow">NEXT AT FIXITFINDIT</p><h2>Trending Finds</h2><p>We’re building a rotating selection of useful discoveries, with product demos where available. Our first edit is still being reviewed.</p><a class="text-link" href="${link('home-improvement')}">Explore the catalog meanwhile →</a></div><div class="home-partner-space"><span class="eyebrow">MORE HOME SOLUTIONS</span><h3>Room for a good recommendation.</h3><p>Future affiliate offers will appear here, clearly labeled. No paid placements are active yet.</p></div></section>
    <section class="home-section home-how shell" id="how"><p class="eyebrow">OUR APPROACH</p><h2>Useful earns its place.</h2><div><article><span>01</span><h3>A real everyday problem.</h3><p>Start with what makes home life easier, cleaner or more organized.</p></article><article><span>02</span><h3>The details matter.</h3><p>We’re reviewing products, delivery options and total costs before opening checkout.</p></article><article><span>03</span><h3>See what you’re getting.</h3><p>Clear product information, with demonstrations when available and cleared for use.</p></article></div></section>
  </main>`;
}
