import {DatabaseSync} from 'node:sqlite';
import {randomUUID} from 'node:crypto';
import {payoutReview} from './payout-review.mjs';
export function createManualPayouts(path,{affiliates,now=Date.now,enabled=false}={}){
 const db=new DatabaseSync(path);db.exec("PRAGMA busy_timeout=5000; CREATE TABLE IF NOT EXISTS partner_paypal(partner_id TEXT PRIMARY KEY,email TEXT NOT NULL,updated_at TEXT NOT NULL); CREATE TABLE IF NOT EXISTS manual_payouts(id TEXT PRIMARY KEY,partner_id TEXT NOT NULL,period TEXT NOT NULL,email TEXT NOT NULL,amount_cents INTEGER NOT NULL,state TEXT NOT NULL,reference TEXT UNIQUE,created_at TEXT NOT NULL,paid_at TEXT, UNIQUE(partner_id,period))");
 const destination=id=>db.prepare('SELECT email,updated_at FROM partner_paypal WHERE partner_id=?').get(id)||null;
 const history=id=>db.prepare('SELECT id,period,amount_cents,state,created_at,paid_at FROM manual_payouts WHERE partner_id=? ORDER BY created_at DESC').all(id);
 function review(id,period){const r=payoutReview(affiliates.list(id),{now:now(),mode:'live',period});const paid=db.prepare("SELECT COALESCE(SUM(amount_cents),0) n FROM manual_payouts WHERE partner_id=? AND state='paid'").get(id).n;const outstanding=Math.max(0,r.eligibleCents-paid),open=db.prepare("SELECT id FROM manual_payouts WHERE partner_id=? AND state='prepared'").get(id);return {...r,previouslyPaidCents:paid,outstandingCents:outstanding,reviewAmountCents:!open&&outstanding>=2500?outstanding:0,existingPreparedId:open?.id||null,destination:destination(id),paymentsEnabled:enabled};}
 return {destination,history,review,
 saveDestination(id,email,confirm){email=String(email||'').trim().toLowerCase();if(!id||email!==String(confirm||'').trim().toLowerCase()||email.length>254||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))throw Error('Enter matching valid PayPal email addresses');db.exec('BEGIN IMMEDIATE');try{if(db.prepare("SELECT id FROM manual_payouts WHERE partner_id=? AND state='prepared'").get(id))throw Error('Contact support before changing payout details during a payout review');db.prepare('INSERT INTO partner_paypal VALUES(?,?,?) ON CONFLICT(partner_id) DO UPDATE SET email=excluded.email,updated_at=excluded.updated_at').run(id,email,new Date(now()).toISOString());db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}},
 prepare(id,period){if(!enabled)throw Error('Live manual payout preparation is disabled');db.exec('BEGIN IMMEDIATE');try{const existing=db.prepare('SELECT * FROM manual_payouts WHERE partner_id=? AND period=?').get(id,period);if(existing){db.exec('COMMIT');return existing;}const r=review(id,period);if(!r.destination||r.reviewAmountCents<2500)throw Error('No eligible payout or missing PayPal email');const key=randomUUID();db.prepare('INSERT INTO manual_payouts(id,partner_id,period,email,amount_cents,state,created_at) VALUES(?,?,?,?,?,?,?)').run(key,id,period,r.destination.email,r.reviewAmountCents,'prepared',new Date(now()).toISOString());db.exec('COMMIT');return db.prepare('SELECT * FROM manual_payouts WHERE id=?').get(key);}catch(e){db.exec('ROLLBACK');throw e;}},
 recordPaid(id,reference,amount){if(!enabled)throw Error('Live payout recording is disabled');if(!/^[A-Za-z0-9-]{8,100}$/.test(reference||''))throw Error('PayPal transaction reference required');db.exec('BEGIN IMMEDIATE');try{const p=db.prepare('SELECT * FROM manual_payouts WHERE id=?').get(id);if(!p||!Number.isSafeInteger(amount)||amount!==p.amount_cents)throw Error('Payout amount mismatch');if(p.state==='paid'){if(p.reference!==reference)throw Error('Payout already recorded');db.exec('COMMIT');return;}if(p.state!=='prepared')throw Error('Prepared payout required');db.prepare("UPDATE manual_payouts SET state='paid',reference=?,paid_at=? WHERE id=?").run(reference,new Date(now()).toISOString(),id);db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}},
 cancelUnsent(id){if(!enabled)throw Error('Live payout recording is disabled');const r=db.prepare("UPDATE manual_payouts SET state='canceled' WHERE id=? AND state='prepared'").run(id);if(!r.changes)throw Error('Only an unsent prepared payout can be canceled');},
 inspect:id=>db.prepare('SELECT * FROM manual_payouts WHERE id=?').get(id),close:()=>db.close()};
}
