import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createOwnerAccess,createOwnerOrdersRoute,owner} from './owner-orders.mjs';
import {createPartnerStore} from './partner-applications.mjs';
test('owner affiliate view protects private applications, approvals require owner and CSRF, live earnings render',async()=>{
 const access=createOwnerAccess(':memory:'),partners=createPartnerStore(':memory:');partners.apply({name:'<img src=x>',email:'private@example.com',brand:'Private Brand'});const app=partners.list()[0],csrf='a'.repeat(48);const session=access.login(access.issue(owner),s=>s===owner.slug?owner:null);
 const route=createOwnerOrdersRoute({access,partners,orders:{listPaid:()=>[],affiliates:{list:()=>[{netCommissionCents:500,pendingRefund:true}]}},worker:{},payouts:{history:()=>[{state:'paid',amount_cents:200}],destination:()=>({email:'paypal@example.com'})}});
 async function run(method='GET',body='',logged=true,path='/owner/orders/affiliates'){const req=Readable.from([body]);req.method=method;req.headers={'content-type':'application/x-www-form-urlencoded',cookie:'fit_owner_csrf='+csrf+(logged?'; fit_owner_session='+session:'')};const res={headers:{},setHeader(k,v){this.headers[k]=v;},writeHead(s,h){this.status=s;Object.assign(this.headers,h);},end(b){this.body=b;}};await route(req,res,new URL('https://www.fixitfindit.com'+path));return res;}
 try{assert.doesNotMatch((await run('GET','',false)).body,/private@example/);const page=await run();assert.match(page.body,/private@example.com/);assert.doesNotMatch(page.body,/<img src=x>/);assert.equal(page.headers['Cache-Control'],'private, no-store');const body='application='+app.id+'&slug=private-brand&csrf='+csrf,post='/owner/orders/affiliates/approve';assert.equal((await run('POST',body,false,post)).status,401);assert.equal((await run('POST','application='+app.id,true,post)).status,403);assert.equal(partners.find('private-brand'),undefined);assert.equal((await run('POST',body,true,post)).status,303);assert.equal(partners.find('private-brand').demo,false);const updated=await run();assert.match(updated.body,/\$5.00/);assert.match(updated.body,/\$3.00/);assert.match(updated.body,/Refund review/);assert.match(updated.body,/paypal@example.com/);assert.equal((await run('POST',body,true,post)).status,400);}finally{access.close();partners.close();}
});
