import {applicationForm} from './partner-application-route.mjs';
export function partnerPage(shell) {
  return shell.replace(/<title>.*?<\/title>/,'<title>Partner Program | FixItFindIt</title>')
    .replace(/<main id="top"[^>]*>[\s\S]*?<\/main>/, `<main id="top" class="shell partner-program">
      <section class="partner-intro"><span class="partner-status">Prelaunch applications open</span><p class="eyebrow">THE FIXITFINDIT PARTNER PROGRAM</p><h1>Your brand.<br>Our store system.</h1><p>Bring useful finds to your audience with your own branded storefront, powered by FixItFindIt.</p><p class="partner-subtext">We’re developing a program with no upfront storefront fee. Apply below for a storefront preview.</p></section>
      <section class="partner-benefits" aria-label="Planned partner benefits"><article><h2>Make it yours</h2><p>A storefront with your name, branding and a shareable link, using our shared product catalog.</p></article><article><h2>Share your finds</h2><p>Promote your storefront to your audience. We’re building the central checkout and order system.</p></article><article><h2>Earn on eligible sales</h2><p>Planned flat 5% commission on eligible product sales through your storefront, excluding sales tax and separately charged shipping.</p></article></section>
      <section class="partner-details"><h2>What needs to be ready first?</h2><p>We’re accepting prelaunch applications while checkout, order tracking and the commission system are completed. The planned rate is 5%. Referrals use the most recently visited approved storefront within 30 days, fixed when a checkout quote is created. Successful refunds reduce commission proportionally; pending refunds hold earnings for review. Payouts will be sent manually through PayPal after monthly review, a 30-day hold, and a $25 minimum balance. Smaller balances carry forward; refund reviews can extend a hold. Remaining eligibility and payment setup must be completed before live enrollment opens.</p><p>Our planned role is to manage the catalog, customer checkout, customer service and fulfillment coordination. Partners would focus on promoting their storefronts.</p><p>There are no guaranteed earnings. Sales depend on your audience, promotion and customer demand.</p><a class="partner-demo-link" href="/shop/home-helper">Explore a demo storefront ↗</a><p class="partner-subtext">The demo does not process purchases or earn commissions.</p></section>
      <section class="partner-faq"><h2>A few things to know</h2><details><summary>Can I apply now?</summary><p>Yes. Apply below for manual review. Approved storefronts remain previews until sales launch.</p></details><details><summary>How much commission will I earn?</summary><p>The planned rate is 5% of eligible product revenue, excluding sales tax and separately charged shipping. Refunds reduce earnings. Sandbox tests and demo storefronts never earn payable commissions.</p></details><details><summary>Do I need to buy inventory?</summary><p>The planned program does not require partners to purchase inventory. Supplier orders would be managed centrally by FixItFindIt.</p></details></section>
    <p><a href="/partners/dashboard">Partner dashboard sign-in →</a></p>${applicationForm()}</main>`).replace(/href="#(?:browse|top)"/g,'href="/"');
}
