import test from 'node:test';
import assert from 'node:assert/strict';
import {Readable} from 'node:stream';
import {createDashboardAccess,createDashboardRoute,dashboardPage} from './partner-dashboard.mjs';
import {payoutReview} from './payout-review.mjs';
const a={id:'partner-a',slug:'alpha',name:'Alpha'},b={id:'partner-b',slug:'beta',name:'Beta'};const find=s=>s==='alpha'?a:s==='beta'?b:null;
test('private dashboard codes are single use, scoped, expiring and revocable',()=>{let now=1;const store=createDashboardAccess(':memory:',{now:()=>now});const code=store.issue(a);assert.equal(store.login('x',find),null);const token=store.login(code,find);assert.equal(store.resolve(token,find).id,a.id);assert.equal(store.login(code,find),null);assert.equal(store.resolve(token,()=>null),null);store.revoke(a.id);assert.equal(store.resolve(token,find),null);const second=store.issue(b);now+=24*3600000;assert.equal(store.login(second,find),null);store.close();});
test('dashboard cannot select another partner or expose data before authentication',async()=>{const access=createDashboardAccess(':memory:');const token=access.login(access.issue(a),find);let requested;const route=createDashboardRoute({access,findPartner:find,affiliates:{list:id=>{requested=id;return [];}}});async function run(cookie='',path='/partners/dashboard?partner=partner-b',method='GET',origin){const req=Readable.from([]);req.method=method;req.headers={cookie,origin};const res={headers:{},setHeader(k,v){this.headers[k]=v;},writeHead(status,h){this.status=status;Object.assign(this.headers,h);},end(body){this.body=body;}};await route(req,res,new URL('https://www.fixitfindit.com'+path));return res;}
 const anonymous=await run();assert.match(anonymous.body,/Access code/);assert.equal(requested,undefined);const signed=await run('fit_partner_session='+token);assert.equal(requested,a.id);assert.match(signed.body,/Alpha/);assert.equal(signed.headers['Cache-Control'],'private, no-store');assert.equal((await run('fit_partner_session='+token,'/partners/dashboard/logout','POST','https://attacker.example')).status,403);assert.equal(access.resolve(token,find).id,a.id);access.close();});
test('payout review excludes test orders, recent orders, refund holds and balances below minimum',()=>{const row={order_id:'one',partner_id:'real',mode:'live',created_at:'2026-01-01T00:00:00Z',netCommissionCents:2500};const opts={now:Date.parse('2026-03-15'),period:'2026-03',mode:'live'};assert.equal(payoutReview([row],opts).reviewAmountCents,2500);assert.equal(payoutReview([{...row,netCommissionCents:2499}],opts).reviewAmountCents,0);for(const change of [{mode:'sandbox'},{partner_id:'demo-test'},{created_at:'2026-02-28'},{pendingRefund:true},{fulfillmentHold:true}])assert.equal(payoutReview([{...row,...change}],opts).reviewAmountCents,0);assert.equal(payoutReview([row],opts).payableCents,0);});
test('dashboard escapes partner names and exposes no customer fields',()=>{const html=dashboardPage({...a,name:'<script>x</script>'},[]);assert.ok(!html.includes('<script>x'));assert.match(html,/&lt;script&gt;/);assert.match(html,/minimum balance/);});
