import {applicationForm} from './partner-application-route.mjs';
export function partnerPage(shell,salesEnabled=false) {
  return shell.replace(/<title>.*?<\/title>/,'<title>Partner Program | FixItFindIt</title>')
    .replace(/<main id="top"[^>]*>[\s\S]*?<\/main>/, `<main id="top" class="shell partner-program">
      <section class="partner-intro"><span class="partner-status">Affiliate applications open</span><p class="eyebrow">THE FIXITFINDIT PARTNER PROGRAM</p><h1>Your brand.<br>Our store system.</h1><p>Bring useful finds to your audience with your own branded storefront, powered by FixItFindIt.</p><p class="partner-subtext">Apply for a branded storefront with no upfront storefront fee. We review each application before approval.</p></section>
      <section class="partner-benefits" aria-label="Partner benefits"><article><h2>Make it yours</h2><p>A storefront with your name, branding and a shareable link, using our shared product catalog.</p></article><article><h2>Share your finds</h2><p>Promote your storefront to your audience. We manage the product catalog, checkout and order coordination.</p></article><article><h2>Earn on eligible sales</h2><p>Flat 5% commission on eligible product sales through your storefront, excluding sales tax and separately charged shipping.</p></article></section>
      <section class="partner-details"><h2>How the program works</h2><p>${salesEnabled?"Live checkout is open. Approved partners can earn 5% on eligible purchases.":"Applications and storefront setup are open. Customer checkout is still closed, so commissions cannot accrue yet. The rate on eligible live purchases will be 5%."} Referrals use the most recently visited approved storefront within 30 days, fixed when a checkout quote is created. Successful refunds reduce commission proportionally; pending refunds hold earnings for review. Payouts will be sent manually through PayPal after monthly review, a 30-day hold, and a $25 minimum balance. Smaller balances carry forward; refund reviews can extend a hold. Approval and PayPal payment details are required before payout.</p><p>We manage the catalog, customer checkout, customer service and fulfillment coordination. Partners focus on promoting their storefronts.</p><p>There are no guaranteed earnings. Sales depend on your audience, promotion and customer demand.</p><a class="partner-demo-link" href="/shop/home-helper">Explore a demo storefront ↗</a><p class="partner-subtext">The demo does not process purchases or earn commissions.</p></section>
      <section class="partner-faq"><h2>A few things to know</h2><details><summary>Can I apply now?</summary><p>Yes. Apply below for manual review. ${salesEnabled?"Approved storefronts can refer live purchases.":"You can set up and share your approved storefront while we finish opening customer checkout."}</p></details><details><summary>How much commission will I earn?</summary><p>The rate is 5% of eligible product revenue, excluding sales tax and separately charged shipping. Refunds reduce earnings. Sandbox tests and demo storefronts never earn payable commissions.</p></details><details><summary>Do I need to buy inventory?</summary><p>The program does not require partners to purchase inventory. Supplier orders are managed centrally by FixItFindIt.</p></details></section>
    <p><a href="/partners/dashboard">Partner dashboard sign-in →</a></p>${applicationForm()}</main>`).replace(/href="#(?:browse|top)"/g,'href="/"');
}
