import test from 'node:test';
import assert from 'node:assert/strict';
import {createOrderStore} from './orders.mjs';
import {createRefundTracking} from './refund-tracking.mjs';
import {createWebhookRoute} from './stripe-webhook.mjs';
import {createFulfillmentWorker} from './fulfillment-worker.mjs';
import {createHmac} from 'node:crypto';
import {Readable} from 'node:stream';
function setup(){const orders=createOrderStore(':memory:');const o=orders.prepare('owner',{productId:'p',variantId:'v',name:'test',retailCents:2000});orders.recordSession({id:'cs_test_a',payment_intent:'pi_a',livemode:false,client_reference_id:'owner',amount_total:2000,currency:'usd',status:'complete',payment_status:'paid',metadata:{purpose:'fixitfindit-product-sandbox',fulfillment:'sandbox-do-not-ship',store_id:'fixitfindit',order_id:o.id,product_id:'p',variant_id:'v',retail_cents:'2000',quantity:'1'}},'evt_paid');return {orders,id:o.id};}
const refund=(status='pending',id='re_a',amount=500)=>({id,amount,status,payment_intent:'pi_a',currency:'usd'});
test('partial/full refunds, duplicates and failures remain separate from payment status',()=>{const {orders,id}=setup();const save=rows=>orders.refunds.save(id,orders.refunds.begin(id),rows);assert.equal(save([refund()]).pendingCents,500);assert.equal(save([refund('succeeded')]).refundedCents,500);assert.equal(save([refund('succeeded')]).refundedCents,500);assert.equal(save([refund('succeeded'),refund('succeeded','re_b',1500)]).refundedCents,2000);assert.equal(orders.get(id).status,'paid_sandbox');assert.equal(save([refund('succeeded'),refund('failed','re_b',1500)]).refundedCents,500);assert.equal(orders.refunds.summary(id).fulfillmentHold,true);orders.close();});
test('stale checks, changed identity, incomplete history and excessive amounts cannot overwrite ledger',()=>{const {orders,id}=setup();const stale=orders.refunds.begin(id);orders.refunds.save(id,orders.refunds.begin(id),[refund('succeeded')]);assert.throws(()=>orders.refunds.save(id,stale,[refund()]));for(const rows of [[],[refund('succeeded','re_a',600)],[{...refund(),payment_intent:'pi_wrong'}],[refund('succeeded','re_a',500),refund('succeeded','re_b',1800)]])assert.throws(()=>orders.refunds.save(id,orders.refunds.begin(id),rows));assert.equal(orders.refunds.summary(id).refundedCents,500);orders.close();});
test('Stripe reconciliation paginates using GET only and validates payment mode/amount',async()=>{const {orders,id}=setup();let calls=0;const request=async(url,options)=>{assert.equal(options.method,undefined);calls++;return {ok:true,json:async()=>url.includes('payment_intents/')?{id:'pi_a',livemode:false,currency:'usd',amount_received:2000}:url.includes('starting_after=')?{object:'list',data:[refund('failed','re_b')],has_more:false}:{object:'list',data:[refund('succeeded')],has_more:true}};};const tracker=createRefundTracking({orders,key:'sk_test_fake',request});assert.equal((await tracker.sync(id)).refundedCents,500);assert.equal(calls,3);await assert.rejects(createRefundTracking({orders,key:'sk_live_fake',request}).sync(id));await assert.rejects(createRefundTracking({orders,key:'sk_test_fake',request:async()=>({ok:true,json:async()=>({id:'pi_a',livemode:true,currency:'usd',amount_received:2000})})}).sync(id));orders.close();});
test('failed API refresh retains prior totals and holds fulfillment on notification',async()=>{const {orders,id}=setup();const tracker=createRefundTracking({orders,key:'sk_test_fake',request:async()=>{throw Error('offline');}});await assert.rejects(tracker.event({data:{object:refund()}}));assert.equal(orders.refunds.summary(id).fulfillmentHold,true);const worker=createFulfillmentWorker({orders,cj:{},catalog:{}});await assert.rejects(worker.submit(id),/Refund review/);await assert.rejects(worker.simulatePayment(id),/Refund review/);orders.close();});
test('signed refund notifications reconcile and failed reconciliation requests retry',async()=>{const {orders,id}=setup();const secret='whsec_test';const event={id:'evt_refund',livemode:false,type:'refund.updated',data:{object:refund()}};const raw=Buffer.from(JSON.stringify(event)),t=Math.floor(Date.now()/1000);const signature='t='+t+',v1='+createHmac('sha256',secret).update(t+'.').update(raw).digest('hex');for(const fail of [false,true]){const req=Readable.from([raw]);req.method='POST';req.headers={'stripe-signature':signature};const res={writeHead(n){this.code=n;},end(){}};await createWebhookRoute({orders,secret,refundTracking:{event:async e=>{assert.equal(e.id,event.id);if(fail)throw Error('offline');}}})(req,res,new URL('https://example.com/webhooks/stripe'));assert.equal(res.code,fail?503:200);}orders.close();});
